services:
  placement:
    image: "daprio/dapr:1.15.3"
    command: ["./placement", "--port", "50006"]
    ports:
      - "50006:50006"

  scheduler:
    image: "daprio/dapr:1.15.3"
    command: ["./scheduler", "--port", "50007"]
    ports:
      - "50007:50007"
    volumes:
      - ./volumes/data/scheduler_data:/data # does not work with named volume

  traefik:
    image: "traefik:v3.1"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.http.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rabbitmq:
    image: "rabbitmq:3.9-management"
    environment:
      - RABBITMQ_DEFAULT_USER=demo
      - RABBITMQ_DEFAULT_PASS=demo
      - RABBITMQ_ERLANG_COOKIE=demo_cookie_1234
    volumes:
      - ./volumes/infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./volumes/infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: "redis:6.2-alpine"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/infra/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data

  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./volumes/infra/postgres:/docker-entrypoint-initdb.d:ro

  ##### Zipkin #####
  zipkin:
    image: "openzipkin/zipkin:2.23.2"
    ports:
      - 9411:9411

  ##### fluent-bit #####
  fluent-bit:
    image: fluent/fluent-bit:3.2
    depends_on:
      - seq-input-gelf
    ports:
      - 24224:24224 # Forward input plugin
      - 24220:24220 # built-in HTTP Server
    volumes:
      - "./volumes/infra/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro"

  ##### Seq #####
  seq:
    image: datalust/seq:2024
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    ports:
      - "8001:80"

  seq-input-gelf:
    image: datalust/seq-input-gelf:3.0
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped

volumes:
  seq_data:
  rabbitmq_data:
  redis_data:
  postgres_data:

networks:
  default:
    name: my_network
    external: true
