services:
  redisinsights:
    image: redislabs/redisinsight
    ports:
      - 5540:5540

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"

networks:
  default:
    name: my_network
    driver: bridge
    external: true
